---

- hosts: development
  user: vagrant
  vars: 
    - mysql_root_password: password
    - rbenv_root: /home/vagrant/.rbenv
    - shell_rc_path: ~/.zshrc
    - curl_file: curl-7.55.1
  roles:
    - { role: mysql, become: yes }
    - ruby
  pre_tasks:
    - name: install packages
      become: yes
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - vim
        - curl
        - wget
        - gcc
        - zsh
        - openssl-devel
        - sqlite-devel
        - readline-devel
        - mysql-devel
        - git
        - tree
        - epel-release
        - gcc-c++
    - name: install nodejs
      become: yes
      yum:
        name: nodejs
        enablerepo: epel
    - name: change zsh
      become: yes
      command: chsh -s /bin/zsh vagrant
    - name: install libcurl
      shell: |
        wget "https://curl.haxx.se/download/{{ curl_file }}.tar.gz"
        tar zxf {{ curl_file}}.tar.gz
        cd {{ curl_file }}
        ./configure
        make
    - name: install libcurl
      become: yes
      shell: |
        cd {{ curl_file }}
        make install
